### PR TITLE
add width property to img elements to stop overflow

### PR DESCRIPTION
**Pull request by ananfito**
I think I fixed the overflow problem you were having with the images. I added `width: 100%` to the image elements so that they could fill the containers the inhabit. 

In terms of responsiveness, I think you're going to run into a similar overflow issue with the header and navbar section when viewed on smaller screens. I'm not sure if you've learned about mobile-first design or building responsive websites yet, but this is something could be addressed by using media queries and relative units.

### CODE REVIEW

**Comment by MojoBoingo** [comment]
So I've studied responsive web design, and I understand the idea of media queries; the part that trips me up about them is how to determine the values and for what. Like say I want the font to resize depending on the viewport, to keep the text legible and sized to match with the display. But I don't know how to arrive at the value; which font size is that? A percentage? Is it something you just have to fiddle with until it fits whatever parameters you're setting? Going to try and work from the code on this  branch in the FCC editor for now, and keep the pull request open with the conversation.

**Comment by MojoBoingo** [comment]
I'm sorry to say it didn't fix the problem. I may not have described it properly. It's still confining the content even as it creates blank space to necessitate a scroll bar.

**Comment by ananfito** [comment]
> So I've studied responsive web design, and I understand the idea of media queries; the part that trips me up about them is how to determine the values and for what. Like say I want the font to resize depending on the viewport, to keep the text legible and sized to match with the display. But I don't know how to arrive at the value; which font size is that? A percentage? Is it something you just have to fiddle with until it fits whatever parameters you're setting? Going to try and work from the code on this branch in the FCC editor for now, and keep the pull request open with the conversation.

The course I mentioned in the Discord thread deals with ^^this vary topic^^: how to know where your break points are for media queries. What should happen with your font size? Your widths, images, etc. 



> I'm sorry to say it didn't fix the problem. I may not have described it properly. It's still confining the content even as it creates blank space to necessitate a scroll bar.

Hmm. Okay, well I can take another look and tinker with it, but maybe tell me more about the details. For example, what is your window width when you encounter this issue? Also, if you can, maybe include a screenshot so I can see visually what you mean.

**Comment by MojoBoingo** [comment]
I'm not sure of the exact dimensions; it's not something I paid attention to in the middle of all this. I'll give you a before and after screenshot in Discord.

**Pull request closed without merging**
